---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - haproxy
  tags:
    - software-installation
    - using-apt
    - haproxy

- name: Install DNS Reactor | wget
  get_url:
    url: "{{ haproxy_dns_reactor_download_source }}"
    dest: /usr/bin/dnsreactor
    mode: 0555
  when: haproxy_dns_reactor_enabled
