---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - haproxy
  tags:
    - software-installation
    - using-apt
    - haproxy

- name: Service Stopped | haproxy
  service:
    state: stopped
    name: haproxy
