---
- { include: repositories.yml, tags: ['package', 'repositories'] }
- { include: packages.yml, tags: ['package', 'install'] }
- { include: monitoring.yml, tags: ['configure', 'monitoring', 'services'] }
- { include: config.yml, tags: ['package', 'configure'] }
- { include: services.yml, tags: ['services'] }
