---
- name: Upload Config | monit | haproxy
  template:
    src: etc/monit/conf.d/haproxy
    dest: /etc/monit/conf.d/haproxy
  notify: Reload Service | monit
  tags:
    - monitoring
    - services
    - haproxy
    - using-monit

- name: Trigger All Callbacks
  meta: flush_handlers

- name: Configure | haproxy | pidfile
  lineinfile:
    state: present
    dest: /etc/init.d/haproxy
    regexp: '^PIDFILE='
    line: "PIDFILE={{ haproxy_pidfile_path }}"
  notify: Reload Service | haproxy
  tags:
    - pidfile
    - service
