---
- name: Import Signing Key | ~vbernat
  apt_key:
    state: present
    keyserver: 'hkp://keyserver.ubuntu.com:80'
    id: '0x505d97a41c61b9cd'
  tags:
    - repository
    - package
    - apt
    - signing-key
    - haproxy

- name: Import Repository | ~vbernat/haproxy-1.5
  apt_repository:
    state: present
    repo: 'deb http://ppa.launchpad.net/vbernat/haproxy-1.5/ubuntu trusty main'
  notify: Update Package Cache
  tags:
    - repository
    - package
    - apt
    - haproxy

- name: Trigger All Callbacks
  meta: flush_handlers
