---
- name: Enable Service | haproxy
  lineinfile:
    state: present
    dest: /etc/default/haproxy
    regexp: 'ENABLED\='
    line: 'ENABLED=1'
  tags:
    - haproxy

- name: Service Started | haproxy
  service:
    state: started
    name: haproxy
  tags:
    - haproxy
