- name: "Make sure {{ haproxy_ssl_certificate_path }} exists"
  file:
    path="{{ haproxy_ssl_certificate_path }}"
    state=directory
    owner=haproxy
    mode=0755
  tags:
    - configuration
    - haproxy

- name: Upload SSL Certificate 
  copy:
    src="data/www/{{ 'production' if environment_tier in ['staging', 'production'] else 'development' }}.pem"
    dest="{{ haproxy_ssl_certificate_path }}{{ haproxy_ssl_certificate_name }}"
    owner=haproxy
    mode=0600
  tags:
    - configuration
    - haproxy